// ============================================================
//  BLOCK PARTY — MODEL DATA
//  To add a new model, copy one of the entries below and fill
//  in your details. No other files need to be changed.
// ============================================================

const COLLECTIONS = {
  ssc: {
    name: "Seaside Suburbs Collection",
    code: "ssc",
    description: "Coastal-inspired furniture with a relaxed, sun-bleached aesthetic.",
  }
};

const MODELS = [
  {
    id: "ssc061",
    name: "Grass Patch",
    collection: "ssc",
    number: "061",
    category: "plants",
    room: ["garden", "outdoor"],
    description: "A small 1x1 patch of grass",
    baseItem: "Birch Trapdoor",
    anvilCode: "ssc061",
    variants: [
      { code: "a", name: "Green", color: "#8fa051" }
      ],
    positions: [
      { code: "",       name: "Default", description: "Standard floor placement" },
      { code: "center", name: "Corner",  description: "Corner between two blocks" },
      { code: "center", name: "Raised Back",  description: "Raises 0.5 up and spawns behind item frame" },
      { code: "center", name: "Raised Forward",  description: "Raises 0.5 up and spawns in front of item frame" },
    ],
    tags: ["grass", "garden", "green", "bush", "plant"],
    colorTags: ["green"],
    images: {
      // format: variantCode -> filename in images/ssc061/
      a: "a.png", 
      pos_default: "ssc061.png",
      pos_corner:  "ssc061corner.png",
      pos_raisedback:  "ssc061raisedback.png",
      pos_raisedforward:  "ssc061raisedforward.png",
    }
  },
  {
    id: "ssc062",
    name: "Tall Untrimmed Bush",
    collection: "ssc",
    number: "062",
    category: "Plants",
    room: ["garden", "outdoor"],
    description: "A skinny, tall, untrimmed bush spanning 1x2",
    baseItem: "Birch Pressure Plate",
    anvilCode: "ssc062",
    variants: [
      { code: "a", name: "Lime", color: "#BEAF59" }
      ],
    positions: [
      { code: "",       name: "Default", description: "Standard floor placement" }
    ],
    tags: ["bush", "tree", "plant", "green", "garden"],
    colorTags: ["green", "yellow"],
    images: {
      a: "a.png",
      pos_default: "ssc062.png",
    }
  },
  {
    id: "ssc063",
    name: "Potted Lemon Tree",
    collection: "ssc",
    number: "063",
    category: "Potted Plants",
    room: ["outdoor", "misc"],
    description: "A potted lemon tree and a potted orange tree, spanning slightly larger than 1x2",
    baseItem: "Birch Button",
    anvilCode: "ssc063",
    variants: [
      { code: "a", name: "Lemon",  color: "#BBA622" },
      { code: "b", name: "Orange",        color: "#D89118" }
    ],
    positions: [
      { code: "",    name: "Default", description: "Standard Block Placement" }
    ],
    tags: ["potted", "plant", "tree", "garden", "green", "orange", "lemon", "fruit"],
    colorTags: ["yellow", "orange", "green", "beige", "brown"],
    images: {
      a: "a.png", b: "b.png",
      pos_default: "ssc063.png"
    }
  },
  {
    id: "ssc064",
    name: "Large River Rocks",
    collection: "ssc",
    number: "064",
    category: "rocks",
    room: ["outdoor", "garden"],
    description: "A trio of river rocks spanning less than 1x1",
    baseItem: "Jungle Log",
    anvilCode: "ssc064",
    variants: [
      { code: "a", name: "Brownstone",  color: "#89837A" },
      { code: "b", name: "Dark Grey",   color: "#575042" },
      { code: "c", name: "Sandstone",  color: "#B6A991" },
      { code: "d", name: "Light Grey",      color: "#B4B2AE" },
      { code: "e", name: "Dark Charcoal",         color: "#4D4D4A" },
      { code: "f", name: "Mauve Grey",   color: "#786663" },
      { code: "g", name: "Mossy Green",      color: "#718E28" }
     ],
    positions: [
      { code: "", name: "Default", description: "Standard Block Placement" },
      { code: "", name: "Back", description: "Placed Back on Block" },
      { code: "", name: "Corner", description: "Placed Corner on Block" },
      { code: "", name: "Raised Back", description: "Raises 0.5 above block, and spawns behind item frame" },
      { code: "", name: "Raised Forward", description: "Raises 0.5 above block and spawns behind item frame" }
    ],
    tags: ["rock", "stone", "pebble", "garden"],
    colorTags: ["black", "brown", "grey"],
    images: {
      a: "a.png", b: "b.png", c: "c.png", d: "d.png", e: "e.png",
      f: "f.png", g: "g.png",
      pos_default: "ssc064.png",
      pos_back: "ssc064back.png",
      pos_corner: "ssc064corner.png",
      pos_raisedback: "ssc064raisedback.png",
      pos_raisedforward: "ssc064raisedforward.png"
    }
  },
  {
    id: "ssc065",
    name: "Classic Wood Pillar",
    collection: "ssc",
    number: "065",
    category: "Structure",
    room: ["Exterior"],
    description: "A thin, white, wood pillar",
    baseItem: "Jungle Wood",
    anvilCode: "ssc065",
    variants: [
      { code: "a", name: "White", color: "#D2D1D0" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Back of block" },
      { code: "innercorner", name: "Inner Corner", description: "Fits into an inner corner" },
      { code: "outercorner", name: "Outer Corner", description: "Fits into an outer corner" }
    ],
    tags: ["pillar", "column", "wood", "wooden", "support", "structural", "classic", "post", "beam", "exterior", "porch", "traditional"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_back: "ssc065back.png",
      pos_innercorner: "ssc065innercorner.png",
      pos_outercorner: "ssc065outercorner.png"
    }
  },
  {
    id: "ssc066",
    name: "Colonial Column",
    collection: "ssc",
    number: "066",
    category: "Structure",
    room: ["Exterior"],
    description: "A thick, brick and stone column reaching 4 blocks high",
    baseItem: "Stripped Jungle Log",
    anvilCode: "ssc066",
    variants: [
      { code: "a", name: "Silver", color: "#D0C8BA" },
      { code: "b", name: "Khaki", color: "#AB9878" },
      { code: "c", name: "Camel", color: "#A89273" },
      { code: "d", name: "Camel", color: "#B08E6D" },
      { code: "e", name: "Oak Brown", color: "#977051" },
      { code: "f", name: "Brown", color: "#8E5935" },
      { code: "g", name: "Russet", color: "#864B35" },
      { code: "h", name: "Mocha", color: "#654A39" },
      { code: "i", name: "Charcoal", color: "#46372E" },
      { code: "j", name: "Medium Gray", color: "#797467" },
      { code: "k", name: "Charcoal", color: "#3A3631" },
      { code: "l", name: "Charcoal", color: "#2D2C2C" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Back of block" },
      { code: "corner", name: "Corner", description: "Corner of block" }
    ],
    tags: ["column", "colonial", "pillar", "support", "structural", "classic", "exterior", "porch", "white", "architectural", "traditional", "decorative", "brick", "stone"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      pos_back: "ssc066back.png",
      pos_corner: "ssc066corner.png"
    }
  },
  {
    id: "ssc067",
    name: "Colonial Spandrel",
    collection: "ssc",
    number: "067",
    category: "Structure",
    room: ["Exterior"],
    description: "A thick, brick and stone beam spanning 1 block wide",
    baseItem: "Stripped Jungle Wood",
    anvilCode: "ssc067",
    variants: [
      { code: "a", name: "Silver", color: "#C9C2B8" },
      { code: "b", name: "Khaki", color: "#A7977A" },
      { code: "c", name: "Light Brown", color: "#9A8569" },
      { code: "d", name: "Light Brown", color: "#A9896B" },
      { code: "e", name: "Oak Brown", color: "#917154" },
      { code: "f", name: "Brown", color: "#8A5B37" },
      { code: "g", name: "Russet", color: "#794330" },
      { code: "h", name: "Mocha", color: "#644A39" },
      { code: "i", name: "Charcoal", color: "#45372F" },
      { code: "j", name: "Medium Gray", color: "#7A7468" },
      { code: "k", name: "Charcoal", color: "#3A3833" },
      { code: "l", name: "Charcoal", color: "#2C2C2C" }
    ],
    positions: [
      { code: "top", name: "Top", description: "Top of block" }
    ],
    tags: ["spandrel", "brick", "stone", "colonial", "decorative", "trim", "architectural", "porch", "bracket", "ornamental", "classic", "exterior"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      pos_top: "ssc067top.png"
    }
  },
  {
    id: "ssc068",
    name: "Colonial Spandrel Center",
    collection: "ssc",
    number: "068",
    category: "Structure",
    room: ["Exterior"],
    description: "A thin, brick and stone wall backsplash spanning 1 block wide",
    baseItem: "Stripped Jungle Wood",
    anvilCode: "ssc068",
    variants: [
      { code: "a", name: "Silver", color: "#CFCABC" },
      { code: "b", name: "Khaki", color: "#A99475" },
      { code: "c", name: "Light Brown", color: "#998669" },
      { code: "d", name: "Camel", color: "#AE8B6A" },
      { code: "e", name: "Oak Brown", color: "#966E50" },
      { code: "f", name: "Brown", color: "#8D5734" },
      { code: "g", name: "Russet", color: "#78412D" },
      { code: "h", name: "Mocha", color: "#644A38" },
      { code: "i", name: "Charcoal", color: "#42352E" },
      { code: "j", name: "Medium Gray", color: "#777266" },
      { code: "k", name: "Charcoal", color: "#363530" },
      { code: "l", name: "Charcoal", color: "#2B2B2B" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["spandrel", "brick", "stone", "colonial", "decorative", "trim", "architectural", "porch", "bracket", "ornamental", "classic", "exterior"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      pos_default: "ssc068.png"
    }
  },
  {
    id: "ssc069",
    name: "Colonial Spandrel Left",
    collection: "ssc",
    number: "069",
    category: "Structure",
    room: ["Exterior"],
    description: "A thin, brick and stone, arched wall backsplash spanning 1x1",
    baseItem: "Stripped Jungle Wood",
    anvilCode: "ssc069",
    variants: [
      { code: "a", name: "Silver", color: "#CFCABC" },
      { code: "b", name: "Khaki", color: "#AA9575" },
      { code: "c", name: "Light Brown", color: "#998769" },
      { code: "d", name: "Camel", color: "#AD8B69" },
      { code: "e", name: "Oak Brown", color: "#966E50" },
      { code: "f", name: "Brown", color: "#8D5834" },
      { code: "g", name: "Russet", color: "#743E29" },
      { code: "h", name: "Mocha", color: "#624937" },
      { code: "i", name: "Charcoal", color: "#42342E" },
      { code: "j", name: "Medium Gray", color: "#777266" },
      { code: "k", name: "Charcoal", color: "#363530" },
      { code: "l", name: "Charcoal", color: "#2A2A2A" }
    ],
    positions: [
      { code: "right", name: "Right", description: "Right side of block" }
    ],
    tags: ["spandrel", "brick", "stone", "colonial", "decorative", "trim", "architectural", "porch", "bracket", "ornamental", "classic", "exterior", "arch"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      pos_right: "ssc069right.png"
    }
  },
  {
    id: "ssc070",
    name: "Coastal Window Box Large",
    collection: "ssc",
    number: "070",
    category: "Window Decorations",
    room: ["Exterior"],
    description: "A wooden, floral coastal window box spanning 3 blocks wide",
    baseItem: "Stripped Jungle Wood",
    anvilCode: "ssc070",
    variants: [
      { code: "a", name: "Gray", color: "#B5AA99" },
      { code: "b", name: "Light Gray", color: "#D9D2C3" },
      { code: "c", name: "Light Gray", color: "#DAD2C3" },
      { code: "d", name: "Light Gray", color: "#DAD2C3" },
      { code: "e", name: "Terracotta", color: "#B04C4C" },
      { code: "f", name: "Light Gray", color: "#DAD2C3" },
      { code: "g", name: "Parchment", color: "#D2C6B2" },
      { code: "h", name: "Gray", color: "#B0A798" },
      { code: "i", name: "Tan", color: "#B3A58B" },
      { code: "j", name: "Medium Gray", color: "#98896C" },
      { code: "k", name: "Cornflower Blue", color: "#6991EF" },
      { code: "l", name: "Moss", color: "#686857" },
      { code: "m", name: "Charcoal", color: "#2F2F2D" },
      { code: "n", name: "Charcoal", color: "#282F38" },
      { code: "o", name: "Tan", color: "#CEB970" },
      { code: "p", name: "Gray", color: "#95A6B3" },
      { code: "q", name: "Gray", color: "#8C9393" },
      { code: "r", name: "Medium Gray", color: "#6A7A71" },
      { code: "s", name: "Dark Green", color: "#2A462A" },
      { code: "t", name: "Moss", color: "#6A7159" },
      { code: "u", name: "Medium Gray", color: "#929377" },
      { code: "v", name: "Khaki", color: "#B9A873" },
      { code: "w", name: "Chocolate", color: "#762A28" },
      { code: "x", name: "Rose", color: "#DAA692" }
    ],
    positions: [
      { code: "center", name: "Center", description: "Center of block" },
      { code: "top", name: "Top", description: "Top of block" },
      { code: "topcenter", name: "Top Center", description: "Center of top of block" }
    ],
    tags: ["window box", "planter", "coastal", "large", "exterior", "flowers", "garden", "wall", "hanging", "outdoor", "floral", "decorative"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      pos_center: "ssc070center.png",
      pos_top: "ssc070top.png",
      pos_topcenter: "ssc070topcenter.png"
    }
  },
  {
    id: "ssc071",
    name: "Coastal Window Box Medium",
    collection: "ssc",
    number: "071",
    category: "Window Decorations",
    room: ["Exterior"],
    description: "A wooden, floral coastal window box spanning 2 blocks wide",
    baseItem: "Jungle Planks",
    anvilCode: "ssc071",
    variants: [
      { code: "a", name: "Gray", color: "#B2A898" },
      { code: "b", name: "Cornflower Blue", color: "#7195EC" },
      { code: "c", name: "Purple", color: "#9270AD" },
      { code: "d", name: "Brick Red", color: "#934851" },
      { code: "e", name: "Terracotta", color: "#B34A4B" },
      { code: "f", name: "Tan", color: "#D2BB6E" },
      { code: "g", name: "Parchment", color: "#D7CAB5" },
      { code: "h", name: "Gray", color: "#B1A697" },
      { code: "i", name: "Tan", color: "#B8A78A" },
      { code: "j", name: "Tan", color: "#CFB86F" },
      { code: "k", name: "Cornflower Blue", color: "#6992F0" },
      { code: "l", name: "Dark Gray", color: "#6C6658" },
      { code: "m", name: "Charcoal", color: "#2F2F2E" },
      { code: "n", name: "Dark Gray", color: "#48474B" },
      { code: "o", name: "Tan", color: "#D0B970" },
      { code: "p", name: "Terracotta", color: "#CC5758" },
      { code: "q", name: "Gray", color: "#929796" },
      { code: "r", name: "Medium Gray", color: "#687870" },
      { code: "s", name: "Charcoal", color: "#2F4833" },
      { code: "t", name: "Medium Gray", color: "#8C8E73" },
      { code: "u", name: "Gray", color: "#AFAD8C" },
      { code: "v", name: "Medium Gray", color: "#8C896F" },
      { code: "w", name: "Medium Gray", color: "#938D73" },
      { code: "x", name: "Plum", color: "#594871" },
      { code: "y", name: "Mocha", color: "#712F36" }
    ],
    positions: [
      { code: "center", name: "Center", description: "Center of block" },
      { code: "top", name: "Top", description: "Top of block" },
      { code: "topcenter", name: "Top Center", description: "Center of top of block" }
    ],
    tags: ["window box", "planter", "coastal", "medium", "exterior", "flowers", "garden", "wall", "hanging", "outdoor", "floral", "decorative"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      pos_center: "ssc071center.png",
      pos_top: "ssc071top.png",
      pos_topcenter: "ssc071topcenter.png"
    }
  },
  {
    id: "ssc072",
    name: "Metal Electric Lantern",
    collection: "ssc",
    number: "072",
    category: "Wall Lighting",
    room: ["Outdoor"],
    description: "A wall-mounted metal electric lantern",
    baseItem: "Jungle Stairs",
    anvilCode: "ssc072",
    variants: [
      { code: "a", name: "Charcoal", color: "#2D2D2D" },
      { code: "b", name: "Gray", color: "#97958F" },
      { code: "c", name: "Parchment", color: "#D0C9B7" },
      { code: "d", name: "Mocha", color: "#564D3B" },
      { code: "e", name: "Walnut", color: "#6D5624" },
      { code: "f", name: "Brown", color: "#916A3E" },
      { code: "g", name: "Khaki", color: "#BBAD64" },
      { code: "h", name: "Medium Gray", color: "#687968" },
      { code: "i", name: "Medium Gray", color: "#706D68" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["lantern", "light", "lamp", "electric", "metal", "outdoor", "wall", "exterior", "lighting", "coastal", "porch", "garden", "decorative"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      pos_default: "ssc072.png"
    }
  },
  {
    id: "ssc073",
    name: "Coastal Lattice Fence",
    collection: "ssc",
    number: "073",
    category: "Fences & Gates",
    room: ["Outdoor"],
    description: "A tall coastal fence reaching 3 blocks high",
    baseItem: "Jungle Slab",
    anvilCode: "ssc073",
    variants: [
      { code: "a", name: "Silver", color: "#D0CABD" },
      { code: "b", name: "Silver", color: "#C1B8A7" },
      { code: "c", name: "Gray", color: "#9B9585" },
      { code: "d", name: "Khaki", color: "#A2947A" },
      { code: "e", name: "Medium Gray", color: "#797367" },
      { code: "f", name: "Brown", color: "#766251" },
      { code: "g", name: "Dark Gray", color: "#515147" },
      { code: "h", name: "Charcoal", color: "#2A2A2A" },
      { code: "i", name: "Charcoal", color: "#282F38" },
      { code: "j", name: "Dark Gray", color: "#344D6A" },
      { code: "k", name: "Gray", color: "#8595A3" },
      { code: "l", name: "Medium Gray", color: "#707C85" },
      { code: "m", name: "Slate Blue", color: "#5D7070" },
      { code: "n", name: "Charcoal", color: "#293A2C" },
      { code: "o", name: "Moss", color: "#6B6C57" },
      { code: "p", name: "Medium Gray", color: "#8F967A" },
      { code: "q", name: "Khaki", color: "#B4A46D" },
      { code: "r", name: "Chocolate", color: "#6A211D" },
      { code: "s", name: "Dusty Rose", color: "#C88C75" },
      { code: "t", name: "Rose", color: "#D4AA98" },
      { code: "u", name: "Silver", color: "#CFC9BC" },
      { code: "v", name: "Camel", color: "#A78D6F" },
      { code: "w", name: "Light Brown", color: "#A8875A" },
      { code: "x", name: "Light Brown", color: "#AB8A67" },
      { code: "y", name: "Oak Brown", color: "#956C4E" },
      { code: "z", name: "Mocha", color: "#5B4434" },
      { code: "aa", name: "Variant 27", color: "#888888" },
      { code: "ab", name: "Variant 28", color: "#888888" },
      { code: "ac", name: "Variant 29", color: "#888888" },
      { code: "ad", name: "Variant 30", color: "#888888" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Back of block" },
      { code: "cornercenter", name: "Corner Center", description: "Corner of block" },
      { code: "front", name: "Front", description: "Center of block" },
      { code: "innercorner", name: "Inner Corner", description: "Placed on front of block" },
      { code: "", name: "Position 5", description: "Fits into an inner corner" }
    ],
    tags: ["fence", "lattice", "coastal", "outdoor", "garden", "yard", "barrier", "decorative", "wood", "exterior", "panel"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      z: "z.png",
      aa: "aa.png",
      ab: "ab.png",
      ac: "ac.png",
      ad: "ad.png",
      pos_back: "ssc073back.png",
      pos_cornercenter: "ssc073cornercenter.png",
      pos_front: "ssc073front.png",
      pos_innercorner: "ssc073innercorner.png",
      pos_default: "ssc073.png"
    }
  },
  {
    id: "ssc074",
    name: "Coastal Lattice Gate",
    collection: "ssc",
    number: "074",
    category: "Fences & Gates",
    room: ["Outdoor"],
    description: "A tall coastal gate spanning 2 x 3",
    baseItem: "Jungle Fence",
    anvilCode: "ssc074",
    variants: [
      { code: "a", name: "Silver", color: "#D0CABD" },
      { code: "b", name: "Silver", color: "#C2B9A8" },
      { code: "c", name: "Gray", color: "#9C9586" },
      { code: "d", name: "Khaki", color: "#A2947A" },
      { code: "e", name: "Medium Gray", color: "#7A7467" },
      { code: "f", name: "Brown", color: "#786353" },
      { code: "g", name: "Dark Gray", color: "#525248" },
      { code: "h", name: "Charcoal", color: "#2B2C2B" },
      { code: "i", name: "Charcoal", color: "#282F38" },
      { code: "j", name: "Dark Gray", color: "#354E6A" },
      { code: "k", name: "Gray", color: "#8596A3" },
      { code: "l", name: "Gray", color: "#8A9393" },
      { code: "m", name: "Slate Blue", color: "#5C7070" },
      { code: "n", name: "Charcoal", color: "#29392B" },
      { code: "o", name: "Moss", color: "#6A6C56" },
      { code: "p", name: "Medium Gray", color: "#909679" },
      { code: "q", name: "Khaki", color: "#B5A46E" },
      { code: "r", name: "Chocolate", color: "#6B211D" },
      { code: "s", name: "Dusty Rose", color: "#C98D75" },
      { code: "t", name: "Rose", color: "#D5AA98" },
      { code: "u", name: "Silver", color: "#CFC9BC" },
      { code: "v", name: "Camel", color: "#AA9071" },
      { code: "w", name: "Light Brown", color: "#A8885A" },
      { code: "x", name: "Camel", color: "#AD8D6A" },
      { code: "y", name: "Oak Brown", color: "#966D4F" },
      { code: "z", name: "Mocha", color: "#684D39" },
      { code: "aa", name: "Variant 27", color: "#888888" },
      { code: "ab", name: "Variant 28", color: "#888888" },
      { code: "ac", name: "Variant 29", color: "#888888" },
      { code: "ad", name: "Variant 30", color: "#888888" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Back of block" },
      { code: "front", name: "Front", description: "Placed on front of block" }
    ],
    tags: ["fence", "lattice", "coastal", "outdoor", "garden", "yard", "barrier", "decorative", "wood", "exterior", "panel", "gate"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      z: "z.png",
      aa: "aa.png",
      ab: "ab.png",
      ac: "ac.png",
      ad: "ad.png",
      pos_back: "ssc074back.png",
      pos_front: "ssc074front.png"
    }
  },
  {
    id: "ssc075",
    name: "Rough Leaf Fern",
    collection: "ssc",
    number: "075",
    category: "Potted Plants",
    room: ["Outdoor", "Misc"],
    description: "A large spiky fern",
    baseItem: "Jungle Fence Gate",
    anvilCode: "ssc075",
    variants: [
      { code: "a", name: "Khaki", color: "#AD9372" },
      { code: "b", name: "Dark Gray", color: "#4A4949" },
      { code: "c", name: "Dark Gray", color: "#514B48" },
      { code: "d", name: "Khaki", color: "#AE9573" },
      { code: "e", name: "Parchment", color: "#D2C8B9" },
      { code: "f", name: "Camel", color: "#AC9272" },
      { code: "g", name: "Gray", color: "#B0AFA8" },
      { code: "h", name: "Camel", color: "#AC9273" },
      { code: "i", name: "Parchment", color: "#D2C9BA" },
      { code: "j", name: "Gray", color: "#B1B0A8" },
      { code: "k", name: "Parchment", color: "#D2C9BA" },
      { code: "l", name: "Silver", color: "#D1C9BA" },
      { code: "m", name: "Gray", color: "#B1AFA8" },
      { code: "n", name: "Gray", color: "#B1AFA8" },
      { code: "o", name: "Gray", color: "#B1B1AB" },
      { code: "p", name: "Khaki", color: "#AD9474" },
      { code: "q", name: "Dark Gray", color: "#4C4947" },
      { code: "r", name: "Dark Gray", color: "#484748" },
      { code: "s", name: "Gray", color: "#B1AFA8" },
      { code: "t", name: "Parchment", color: "#CFC49B" },
      { code: "u", name: "Parchment", color: "#D2C8B9" },
      { code: "v", name: "Khaki", color: "#AC9372" },
      { code: "w", name: "Silver", color: "#D1C9BA" },
      { code: "x", name: "Parchment", color: "#D2C9BA" },
      { code: "y", name: "Camel", color: "#AC8D74" },
      { code: "z", name: "Light Brown", color: "#A98949" },
      { code: "aa", name: "Variant 27", color: "#888888" },
      { code: "ab", name: "Variant 28", color: "#888888" },
      { code: "ac", name: "Variant 29", color: "#888888" },
      { code: "ad", name: "Variant 30", color: "#888888" }
    ],
    positions: [
      { code: "corner", name: "Corner", description: "Corner of block" },
      { code: "raisedback", name: "Raised Back", description: "Raises 0.5 above block and appears behind item frame" },
      { code: "raisedforward", name: "Raised Forward", description: "Raises 0.5 above block and appears infront of item frame" }
    ],
    tags: ["fern", "plant", "leaf", "rough", "nature", "garden", "green", "foliage", "botanical", "outdoor", "pot", "potted", "planter"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      z: "z.png",
      aa: "aa.png",
      ab: "ab.png",
      ac: "ac.png",
      ad: "ad.png",
      pos_corner: "ssc075corner.png",
      pos_raisedback: "ssc075raisedback.png",
      pos_raisedforward: "ssc075raisedforward.png"
    }
  },
  {
    id: "ssc076",
    name: "Hanging Fern Sphere",
    collection: "ssc",
    number: "076",
    category: "Potted Plants",
    room: ["Outdoor", "Misc", "Exterior"],
    description: "A ceiling-mounted hanging potted spherical fern",
    baseItem: "Jungle Trapdoor",
    anvilCode: "ssc076",
    variants: [
      { code: "a", name: "Olive", color: "#557225" },
      { code: "b", name: "Forest Green", color: "#386B30" },
      { code: "c", name: "Dark Green", color: "#0C4D37" },
      { code: "d", name: "Eggplant", color: "#572651" }
    ],
    positions: [
      { code: "corner", name: "Corner", description: "Corner of block" }
    ],
    tags: ["fern", "plant", "sphere", "ball", "topiary", "hanging", "nature", "garden", "green", "foliage", "bush", "botanical", "outdoor", "patio", "pot", "planter", "coastal"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      pos_corner: "ssc076corner.png"
    }
  },
  {
    id: "ssc077",
    name: "Floor Hammock Stand",
    collection: "ssc",
    number: "077",
    category: "Outdoor Seating",
    room: ["Outdoor", "Exterior"],
    description: "A propped hammock with a wood floor stand, spanning 2 blocks wide",
    baseItem: "Jungle Pressure Plate",
    anvilCode: "ssc077",
    variants: [
      { code: "a", name: "Gray", color: "#ACB695" },
      { code: "b", name: "Medium Gray", color: "#798A6F" },
      { code: "c", name: "Silver", color: "#AFC7D2" },
      { code: "d", name: "Dark Gray", color: "#3A5663" },
      { code: "e", name: "Peach", color: "#F0B6A9" },
      { code: "f", name: "Light Gray", color: "#D8CEC5" },
      { code: "g", name: "Brown", color: "#856958" },
      { code: "h", name: "Terracotta", color: "#B45A45" },
      { code: "i", name: "Coral", color: "#D98556" },
      { code: "j", name: "Tan", color: "#D3B477" },
      { code: "k", name: "Off White", color: "#EDECEC" },
      { code: "l", name: "Medium Gray", color: "#8E8E8C" },
      { code: "m", name: "Dark Gray", color: "#434344" }
    ],
    positions: [
      { code: "center", name: "Center", description: "Center of block" }
    ],
    tags: ["hammock", "stand", "floor", "fabric", "rope", "cloth", "swing", "relax", "lounge", "coastal", "boho", "outdoor", "bedroom", "patio", "beach", "hanging", "woven", "colorful"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      pos_center: "ssc077center.png"
    }
  },
  {
    id: "ssc078",
    name: "Plastic Storage Bin",
    collection: "ssc",
    number: "078",
    category: "Utility",
    room: ["Outdoor", "Exterior", "Misc", "Garage"],
    description: "A stack of two plastic storage bins",
    baseItem: "Jungle Button",
    anvilCode: "ssc078",
    variants: [
      { code: "a", name: "Gray", color: "#9A9B9A" },
      { code: "b", name: "Gray", color: "#999B9A" },
      { code: "c", name: "Gray", color: "#999998" },
      { code: "d", name: "Gray", color: "#9A9B9A" },
      { code: "e", name: "Gray", color: "#9B9B9A" },
      { code: "f", name: "Gray", color: "#9A9B9A" },
      { code: "g", name: "Gray", color: "#9A9B9A" },
      { code: "h", name: "Gray", color: "#9A9A99" },
      { code: "i", name: "Gray", color: "#9A9B99" },
      { code: "j", name: "Gray", color: "#999A99" },
      { code: "k", name: "Gray", color: "#9A9B9A" },
      { code: "l", name: "Moss", color: "#758862" },
      { code: "m", name: "Sky Blue", color: "#97BCCB" },
      { code: "n", name: "Dark Gray", color: "#374C5B" },
      { code: "o", name: "Peach", color: "#E9B2AC" },
      { code: "p", name: "Gray", color: "#B6A59B" },
      { code: "q", name: "Walnut", color: "#715646" },
      { code: "r", name: "Terracotta", color: "#CC5950" },
      { code: "s", name: "Camel", color: "#BE9564" },
      { code: "t", name: "Silver", color: "#C9C6BF" },
      { code: "u", name: "Charcoal", color: "#313031" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["bin", "storage", "plastic", "container", "box", "outdoor", "garage", "utility", "organizer", "functional", "modern"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      pos_default: "ssc078.png"
    }
  },
  {
    id: "ssc079",
    name: "Wooden Outdoor Bench",
    collection: "ssc",
    number: "079",
    category: "Outdoor Seating",
    room: ["Outdoor", "Hallway", "Garage"],
    description: "A wooden outdoor bench spanning 2 blocks wide",
    baseItem: "Acacia Log",
    anvilCode: "ssc079",
    variants: [
      { code: "a", name: "Charcoal", color: "#303030" },
      { code: "b", name: "Light Gray", color: "#D8D9D8" },
      { code: "c", name: "Parchment", color: "#C7B89B" },
      { code: "d", name: "Brown", color: "#755749" },
      { code: "e", name: "Dark Brown", color: "#3B2B22" },
      { code: "f", name: "Medium Gray", color: "#746C68" },
      { code: "g", name: "Denim", color: "#586379" },
      { code: "h", name: "Chocolate", color: "#753310" },
      { code: "i", name: "Oak Brown", color: "#997148" }
    ],
    positions: [
      { code: "center", name: "Center", description: "Center of block" }
    ],
    tags: ["bench", "seat", "wood", "wooden", "outdoor", "garden", "patio", "seating", "furniture", "park", "classic", "exterior"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      pos_center: "ssc079center.png"
    }
  },
  {
    id: "ssc080",
    name: "Standing Fairy Lights",
    collection: "ssc",
    number: "080",
    category: "Floor Lighting",
    room: ["Outdoor"],
    description: "Two poles holding a string of large fairy lights",
    baseItem: "Acacia Wood",
    anvilCode: "ssc080",
    variants: [
      { code: "a", name: "Oak Brown", color: "#966E4E" },
      { code: "b", name: "Light Brown", color: "#B68858" },
      { code: "c", name: "Oak Brown", color: "#976C4A" },
      { code: "d", name: "Camel", color: "#B88C65" },
      { code: "e", name: "Camel", color: "#AE8B6A" },
      { code: "f", name: "Oak Brown", color: "#957051" },
      { code: "g", name: "Sienna", color: "#92502E" },
      { code: "h", name: "Sienna", color: "#93502E" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["fairy lights", "lights", "string lights", "standing", "floor", "lamp", "glow", "ambiance", "outdoor", "patio", "boho", "decorative", "lighting", "twinkle"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      pos_default: "ssc080.png"
    }
  },
  {
    id: "ssc081",
    name: "Ceramic Potted Flowers",
    collection: "ssc",
    number: "081",
    category: "Potted Plants",
    room: ["Outdoor", "Misc"],
    description: "A round pot filled with leaves and flowers",
    baseItem: "Stripped Acacia Log",
    anvilCode: "ssc081",
    variants: [
      { code: "a", name: "Copper", color: "#BC6741" },
      { code: "b", name: "Silver", color: "#CFC8BC" },
      { code: "c", name: "Charcoal", color: "#393432" },
      { code: "d", name: "Tan", color: "#CEAE75" },
      { code: "e", name: "Medium Gray", color: "#738775" },
      { code: "f", name: "Gray", color: "#8DA5B5" },
      { code: "g", name: "Medium Gray", color: "#8A75A1" },
      { code: "h", name: "Dusty Rose", color: "#B88892" },
      { code: "i", name: "Camel", color: "#B39171" },
      { code: "j", name: "Tan", color: "#B9AC92" },
      { code: "k", name: "Brown", color: "#8B6D4D" }
    ],
    positions: [
      { code: "corner", name: "Corner", description: "Corner of block" },
      { code: "raisedback", name: "Raised Back", description: "Raises 0.5 above block and appears behind item frame" },
      { code: "raisedforward", name: "Raised Forward", description: "Raises 0.5 above block and appears infront of item frame" }
    ],
    tags: ["pot", "ceramic", "flowers", "floral", "plant", "potted", "garden", "colorful", "decorative", "indoor", "outdoor", "botanical"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      pos_corner: "ssc081corner.png",
      pos_raisedback: "ssc081raisedback.png",
      pos_raisedforward: "ssc081raisedforward.png"
    }
  },
  {
    id: "ssc082",
    name: "Wall Electricity Meter",
    collection: "ssc",
    number: "082",
    category: "Utility",
    room: ["Exterior", "Garage"],
    description: "A metal wall electricity meter",
    baseItem: "Stripped Acacia Wood",
    anvilCode: "ssc082",
    variants: [
      { code: "a", name: "Gray", color: "#9A938D" },
      { code: "b", name: "Brown", color: "#7B653F" },
      { code: "c", name: "Dark Gray", color: "#565656" },
      { code: "d", name: "Charcoal", color: "#313130" },
      { code: "e", name: "Gray", color: "#ABABAB" },
      { code: "f", name: "Light Blue", color: "#7793B7" },
      { code: "g", name: "Cobalt Blue", color: "#1E1EB5" },
      { code: "h", name: "Mauve", color: "#B67777" }
    ],
    positions: [
      { code: "top", name: "Top", description: "Top of block" }
    ],
    tags: ["electricity", "meter", "electrical", "utility", "wall", "suburban", "realistic", "exterior", "gauge", "box", "panel", "moden", "functional", "detail", "house"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      pos_top: "ssc082top.png"
    }
  },
  {
    id: "ssc083",
    name: "Industrial Wall Pipe",
    collection: "ssc",
    number: "083",
    category: "Utility",
    room: ["Exterior", "Garage"],
    description: "Three metal wall pipes",
    baseItem: "Acacia Planks",
    anvilCode: "ssc083",
    variants: [
      { code: "a", name: "Copper", color: "#B17048" },
      { code: "b", name: "Dark Green", color: "#294527" },
      { code: "c", name: "Dark Gray", color: "#4B526A" },
      { code: "d", name: "Medium Gray", color: "#73706F" },
      { code: "e", name: "Moss", color: "#737247" }
    ],
    positions: [
      { code: "top", name: "Top", description: "Top of block" }
    ],
    tags: ["pipe", "wall", "industrial", "plumbing", "metal", "exterior", "utility", "functional", "detail", "modern", "urban", "realistic"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      pos_top: "ssc083top.png"
    }
  },
  {
    id: "ssc084",
    name: "Tiled Wall Backsplash",
    collection: "ssc",
    number: "084",
    category: "Wall Decorations",
    room: ["Exterior", "Kitchen", "Bathroom", "Misc"],
    description: "A 3/4 block tall tiled wall backsplash",
    baseItem: "Acacia Stairs",
    anvilCode: "ssc084",
    variants: [
      { code: "a", name: "Silver", color: "#CAC3BC" },
      { code: "b", name: "Silver", color: "#BCB0A3" },
      { code: "c", name: "Khaki", color: "#AF9879" },
      { code: "d", name: "Khaki", color: "#B59A77" },
      { code: "e", name: "Light Brown", color: "#AD825A" },
      { code: "f", name: "Chocolate", color: "#5B3726" },
      { code: "g", name: "Dark Brown", color: "#352922" },
      { code: "h", name: "Charcoal", color: "#2C2C2B" },
      { code: "i", name: "Medium Gray", color: "#84796A" },
      { code: "j", name: "Dark Gray", color: "#5B5D57" },
      { code: "k", name: "Dark Gray", color: "#54593E" },
      { code: "l", name: "Moss", color: "#7C7856" },
      { code: "m", name: "Charcoal", color: "#433D2E" },
      { code: "n", name: "Mocha", color: "#534A2D" },
      { code: "o", name: "Charcoal", color: "#272C31" },
      { code: "p", name: "Slate Blue", color: "#656F6F" },
      { code: "q", name: "Dark Brown", color: "#472B29" },
      { code: "r", name: "Chocolate", color: "#653123" },
      { code: "s", name: "Light Brown", color: "#A57964" },
      { code: "t", name: "Silver", color: "#CBC4BD" },
      { code: "u", name: "Silver", color: "#CAC3BC" },
      { code: "v", name: "Silver", color: "#CCC3BB" },
      { code: "w", name: "Gray", color: "#919592" },
      { code: "x", name: "Brown", color: "#746846" },
      { code: "y", name: "Silver", color: "#CAC3BC" },
      { code: "z", name: "Silver", color: "#BCB1A4" },
      { code: "aa", name: "Variant 27", color: "#888888" },
      { code: "ab", name: "Variant 28", color: "#888888" },
      { code: "ac", name: "Variant 29", color: "#888888" },
      { code: "ad", name: "Variant 30", color: "#888888" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["tile", "backsplash", "wall", "kitchen", "bathroom", "tiled", "pattern", "interior", "modern", "decorative", "ceramic"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      z: "z.png",
      aa: "aa.png",
      ab: "ab.png",
      ac: "ac.png",
      ad: "ad.png",
      pos_default: "ssc084.png"
    }
  },
  {
    id: "ssc085",
    name: "Modern Mailbox",
    collection: "ssc",
    number: "085",
    category: "Wall Decorations",
    room: ["Exterior"],
    description: "A wall-mounted metal mailbox",
    baseItem: "Acacia Slab",
    anvilCode: "ssc085",
    variants: [
      { code: "a", name: "Gray", color: "#A59A8B" },
      { code: "b", name: "Gray", color: "#ABA399" },
      { code: "c", name: "Gray", color: "#A5968C" },
      { code: "d", name: "Gray", color: "#929190" },
      { code: "e", name: "Brown", color: "#786548" },
      { code: "f", name: "Walnut", color: "#70552C" },
      { code: "g", name: "Dark Gray", color: "#6D5649" },
      { code: "h", name: "Charcoal", color: "#423B31" },
      { code: "i", name: "Charcoal", color: "#3A3937" },
      { code: "j", name: "Charcoal", color: "#312D28" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["mailbox", "mail", "postal", "letter", "box", "wall", "exterior", "outdoor", "suburban", "modern", "sleek", "horizontal", "slatted", "house", "entrance"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      pos_default: "ssc085.png"
    }
  },
  {
    id: "ssc086",
    name: "Coastal Window Box Small",
    collection: "ssc",
    number: "086",
    category: "Window Decorations",
    room: ["Exterior"],
    description: "A wooden, floral coastal window box spanning 1 block wide",
    baseItem: "Acacia Fence",
    anvilCode: "ssc086",
    variants: [
      { code: "a", name: "Gray", color: "#B0A797" },
      { code: "b", name: "Linen", color: "#E3DACA" },
      { code: "c", name: "Violet", color: "#74558F" },
      { code: "d", name: "Violet", color: "#74558F" },
      { code: "e", name: "Brick Red", color: "#AE4849" },
      { code: "f", name: "Tan", color: "#D1B86B" },
      { code: "g", name: "Parchment", color: "#D5C7B4" },
      { code: "h", name: "Gray", color: "#B3AA9B" },
      { code: "i", name: "Tan", color: "#B6A98D" },
      { code: "j", name: "Tan", color: "#D0B76B" },
      { code: "k", name: "Cornflower Blue", color: "#6B95EF" },
      { code: "l", name: "Dark Gray", color: "#6C6457" },
      { code: "m", name: "Charcoal", color: "#323131" },
      { code: "n", name: "Violet", color: "#6F578F" },
      { code: "o", name: "Tan", color: "#D0B86C" },
      { code: "p", name: "Gray", color: "#95A4B0" },
      { code: "q", name: "Gray", color: "#939896" },
      { code: "r", name: "Medium Gray", color: "#778C8C" },
      { code: "s", name: "Dark Green", color: "#2B492B" },
      { code: "t", name: "Medium Gray", color: "#8C8E74" },
      { code: "u", name: "Gray", color: "#ACAA8B" },
      { code: "v", name: "Tan", color: "#B7A68F" },
      { code: "w", name: "Russet", color: "#8A3431" },
      { code: "x", name: "Violet", color: "#705490" },
      { code: "y", name: "Blush", color: "#EBC4B3" }
    ],
    positions: [
      { code: "top", name: "Top", description: "Top of block" }
    ],
    tags: ["window box", "planter", "coastal", "small", "exterior", "flowers", "garden", "wall", "hanging", "outdoor", "floral", "decorative"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      pos_top: "ssc086top.png"
    }
  },
  {
    id: "ssc087",
    name: "Wall Fairy Lights",
    collection: "ssc",
    number: "087",
    category: "Wall Lighting",
    room: ["Exterior", "Bedroom", "Living", "Hallway"],
    description: "A 3 block wide string of wall fairy lights",
    baseItem: "Acacia Fence Gate",
    anvilCode: "ssc087",
    variants: [
      { code: "a", name: "Parchment", color: "#D2C7B6" },
      { code: "b", name: "Parchment", color: "#D4C7B4" },
      { code: "c", name: "Parchment", color: "#CDB899" },
      { code: "d", name: "Parchment", color: "#D2C7B5" },
      { code: "e", name: "Medium Gray", color: "#6B7A6C" },
      { code: "f", name: "Charcoal", color: "#2D3134" },
      { code: "g", name: "Parchment", color: "#D5C9B6" },
      { code: "h", name: "Parchment", color: "#D3C7B4" },
      { code: "i", name: "Parchment", color: "#D3C8B5" },
      { code: "j", name: "Gray", color: "#9AA7B1" },
      { code: "k", name: "Silver", color: "#C8CCB9" },
      { code: "l", name: "Coral", color: "#DB8863" },
      { code: "m", name: "Gold", color: "#DEAB27" },
      { code: "n", name: "Parchment", color: "#D3C8B6" },
      { code: "o", name: "Gray", color: "#A8B2B5" },
      { code: "p", name: "Silver", color: "#B7ABB5" },
      { code: "q", name: "Silver", color: "#D0B3B1" }
    ],
    positions: [
      { code: "ceilingcenter", name: "Ceiling Center", description: "Placed on center of ceiling" },
      { code: "ceilingfront", name: "Ceiling Front", description: "Placed on front of ceiling" },
      { code: "wall", name: "Wall", description: "Placed on wall" }
    ],
    tags: ["fairy lights", "lights", "string lights", "wall", "glow", "ambiance", "indoor", "bedroom", "boho", "decorative", "lighting", "twinkle", "hanging"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      pos_ceilingcenter: "ssc087ceilingcenter.png",
      pos_ceilingfront: "ssc087ceilingfront.png",
      pos_wall: "ssc087wall.png"
    }
  },
  {
    id: "ssc088",
    name: "Medinilla Flowers",
    collection: "ssc",
    number: "088",
    category: "Potted Plants",
    room: ["Outdoor", "Misc"],
    description: "A pot with Medinilla flowers",
    baseItem: "Acacia Trapdoor",
    anvilCode: "ssc088",
    variants: [
      { code: "a", name: "Gray", color: "#989089" },
      { code: "b", name: "Dusty Rose", color: "#B69B92" },
      { code: "c", name: "Brown", color: "#8D6648" },
      { code: "d", name: "Chocolate", color: "#4E3123" },
      { code: "e", name: "Charcoal", color: "#403824" },
      { code: "f", name: "Charcoal", color: "#30302C" },
      { code: "g", name: "Dark Gray", color: "#32484C" },
      { code: "h", name: "Chocolate", color: "#5C2721" }
    ],
    positions: [
      { code: "corner", name: "Corner", description: "Corner of block" },
      { code: "raisedback", name: "Raised Back", description: "Raises 0.5 above block and appears behind item frame" },
      { code: "raisedforward", name: "Raised Forward", description: "Raises 0.5 above block and appears infront of item frame" }
    ],
    tags: ["medinilla", "flowers", "floral", "plant", "pink", "tropical", "botanical", "decorative", "indoor", "potted", "exotic", "flower"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      pos_corner: "ssc088corner.png",
      pos_raisedback: "ssc088raisedback.png",
      pos_raisedforward: "ssc088raisedforward.png"
    }
  },
  {
    id: "ssc089",
    name: "Soft Bedroom Bench",
    collection: "ssc",
    number: "089",
    category: "Sofas & Loveseats",
    room: ["Outdoor", "Living", "Bedroom", "Hallway"],
    description: "A short, cushioned bedroom bench spanning 2 blocks wide",
    baseItem: "Acacia Pressure Plate",
    anvilCode: "ssc089",
    variants: [
      { code: "a", name: "Medium Blue", color: "#6997A6" },
      { code: "b", name: "Medium Blue", color: "#6997A6" },
      { code: "c", name: "Medium Gray", color: "#8C8C8C" },
      { code: "d", name: "Medium Gray", color: "#8C8C8C" },
      { code: "e", name: "Medium Blue", color: "#6997A6" },
      { code: "f", name: "Medium Blue", color: "#6997A6" },
      { code: "g", name: "Charcoal", color: "#323232" },
      { code: "h", name: "Medium Blue", color: "#6997A6" },
      { code: "i", name: "Dark Gray", color: "#324C67" },
      { code: "j", name: "Chocolate", color: "#493325" },
      { code: "k", name: "Camel", color: "#AB8B68" },
      { code: "l", name: "Light Brown", color: "#A88B6B" },
      { code: "m", name: "Medium Gray", color: "#8C8C8C" },
      { code: "n", name: "Light Gray", color: "#CFD0CF" },
      { code: "o", name: "Light Brown", color: "#A78B6A" },
      { code: "p", name: "Dark Gray", color: "#474E39" },
      { code: "q", name: "Charcoal", color: "#323231" },
      { code: "r", name: "Oak Brown", color: "#956D51" },
      { code: "s", name: "Dark Gray", color: "#324B67" },
      { code: "t", name: "Chocolate", color: "#473526" },
      { code: "u", name: "Light Gray", color: "#CECDCE" },
      { code: "v", name: "Light Gray", color: "#CDCDCB" },
      { code: "w", name: "Medium Gray", color: "#8F8F8D" },
      { code: "x", name: "Light Gray", color: "#CECECE" },
      { code: "y", name: "Light Gray", color: "#CECDCE" },
      { code: "z", name: "Light Gray", color: "#CECDCE" },
      { code: "aa", name: "Variant 27", color: "#888888" },
      { code: "ab", name: "Variant 28", color: "#888888" },
      { code: "ac", name: "Variant 29", color: "#888888" },
      { code: "ad", name: "Variant 30", color: "#888888" },
      { code: "ae", name: "Variant 31", color: "#888888" },
      { code: "af", name: "Variant 32", color: "#888888" },
      { code: "ag", name: "Variant 33", color: "#888888" },
      { code: "ah", name: "Variant 34", color: "#888888" },
      { code: "ai", name: "Variant 35", color: "#888888" },
      { code: "aj", name: "Variant 36", color: "#888888" },
      { code: "ak", name: "Variant 37", color: "#888888" },
      { code: "al", name: "Variant 38", color: "#888888" },
      { code: "am", name: "Variant 39", color: "#888888" },
      { code: "an", name: "Variant 40", color: "#888888" }
    ],
    positions: [
      { code: "center", name: "Center", description: "Center of block" }
    ],
    tags: ["bench", "seat", "bedroom", "soft", "upholstered", "fabric", "indoor", "furniture", "foot of bed", "seating", "cozy", "padded"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      l: "l.png",
      m: "m.png",
      n: "n.png",
      o: "o.png",
      p: "p.png",
      q: "q.png",
      r: "r.png",
      s: "s.png",
      t: "t.png",
      u: "u.png",
      v: "v.png",
      w: "w.png",
      x: "x.png",
      y: "y.png",
      z: "z.png",
      aa: "aa.png",
      ab: "ab.png",
      ac: "ac.png",
      ad: "ad.png",
      ae: "ae.png",
      af: "af.png",
      ag: "ag.png",
      ah: "ah.png",
      ai: "ai.png",
      aj: "aj.png",
      ak: "ak.png",
      al: "al.png",
      am: "am.png",
      an: "an.png",
      pos_center: "ssc089center.png"
    }
  },
  {
    id: "ssc090",
    name: "Cottage Fence",
    collection: "ssc",
    number: "090",
    category: "Fences & Gates",
    room: ["Outdoor", "Exterior"],
    description: "A classic white picket fence",
    baseItem: "Dark Oak Log",
    anvilCode: "ssc090",
    variants: [
      { code: "a", name: "Light Gray", color: "#DDDDDD" },
      { code: "b", name: "Light Blue", color: "#74B2C9" },
      { code: "c", name: "Sage", color: "#88A589" },
      { code: "d", name: "Gray", color: "#A89A89" },
      { code: "e", name: "Dusty Rose", color: "#D09891" },
      { code: "f", name: "Gray", color: "#A6988B" },
      { code: "g", name: "Brown", color: "#866A51" },
      { code: "h", name: "Mocha", color: "#574339" },
      { code: "i", name: "Charcoal", color: "#3D3D3D" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Back of block" },
      { code: "front", name: "Front", description: "Placed on front of block" },
      { code: "innercorner", name: "Inner Corner", description: "Fits into an inner corner" },
      { code: "outercorner", name: "Outer Corner", description: "Fits into an outer corner" }

    ],
    tags: ["fence", "cottage", "outdoor", "garden", "yard", "barrier", "decorative", "wood", "exterior", "panel", "rustic", "classic"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      pos_back: "ssc090back.png",
      pos_front: "ssc090front.png",
      pos_innercorner: "ssc090innercorner.png",
      pos_outercorner: "ssc090outercorner.png"
    }
  },
  {
    id: "ssc091",
    name: "Classic Support Beam",
    collection: "ssc",
    number: "091",
    category: "Structure",
    room: ["Exterior"],
    description: "A thick, wooden support beam for wall and ceiling",
    baseItem: "Dark Oak Wood",
    anvilCode: "ssc091",
    variants: [
      { code: "a", name: "Russet", color: "#754411" }
    ],
    positions: [
      { code: "front", name: "Front", description: "Placed on front of block" }
    ],
    tags: ["beam", "support", "structural", "classic", "wood", "wooden", "architectural", "exterior", "porch", "post", "traditional", "column"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_front: "ssc091front.png"
    }
  },
  {
    id: "ssc092",
    name: "Classic Brick Chimney",
    collection: "ssc",
    number: "092",
    category: "Roof Decorations",
    room: ["Exterior"],
    description: "A tall brick chimney",
    baseItem: "Stripped Dark Oak Log",
    anvilCode: "ssc092",
    variants: [
      { code: "a", name: "Brown", color: "#906659" },
      { code: "b", name: "Medium Gray", color: "#988F87" },
      { code: "c", name: "Brown", color: "#70594B" },
      { code: "d", name: "Dark Gray", color: "#545353" },
      { code: "e", name: "Gray", color: "#B5A994" },
      { code: "f", name: "Medium Gray", color: "#726F6D" },
      { code: "g", name: "Moss", color: "#756B53" },
      { code: "h", name: "Gray", color: "#ADADAB" },
      { code: "i", name: "Charcoal", color: "#313031" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Appears at back of block" }
    ],
    tags: ["chimney", "brick", "classic", "exterior", "roof", "fireplace", "traditional", "architectural", "house", "stack", "masonry"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      pos_back: "ssc092back.png"
    }
  },
  {
    id: "ssc093",
    name: "HVAC Vent",
    collection: "ssc",
    number: "093",
    category: "Utility",
    room: ["Exterior", "Outdoor", "Misc"],
    description: "A large 2x2 HVAC roof vent",
    baseItem: "Stripped Dark Oak Wood",
    anvilCode: "ssc093",
    variants: [
      { code: "a", name: "Charcoal", color: "#D8BC8B" }
    ],
    positions: [
      { code: "", name: "Default", description: "Standard placement" }
    ],
    tags: ["hvac", "vent", "air", "conditioning", "exterior", "wall", "utility", "functional", "roof", "yard", "realistic", "detail", "modern", "house", "mechanical"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_default: "ssc093.png"
    }
  },
  {
    id: "ssc094",
    name: "Coastal Brick Chimney",
    collection: "ssc",
    number: "094",
    category: "Roof Decorations",
    room: ["Exterior"],
    description: "A coastal brick chimney",
    baseItem: "Dark Oak Planks",
    anvilCode: "ssc094",
    variants: [
      { code: "a", name: "Medium Gray", color: "#75736E" },
      { code: "b", name: "Mocha", color: "#784A49" },
      { code: "c", name: "Mocha", color: "#6C5447" },
      { code: "d", name: "Dark Gray", color: "#504F4F" },
      { code: "e", name: "Medium Gray", color: "#8C8A8D" },
      { code: "f", name: "Dark Gray", color: "#504C48" },
      { code: "g", name: "Dark Gray", color: "#544E48" },
      { code: "h", name: "Chocolate", color: "#4E3528" },
      { code: "i", name: "Dark Brown", color: "#552525" },
      { code: "j", name: "Mocha", color: "#6F5049" },
      { code: "k", name: "Dark Gray", color: "#504E47" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Appears at back of block" }
    ],
    tags: ["chimney", "brick", "classic", "coastal", "exterior", "roof", "fireplace", "architectural", "house", "stack", "masonry", "beach", "traditional"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      pos_back: "ssc094back.png"
    }
  },
  {
    id: "ssc095",
    name: "Ceramic Pot",
    collection: "ssc",
    number: "095",
    category: "Decorative Sculptures",
    room: ["Outdoor", "Misc", "Living", "Garage"],
    description: "A round ceramic pot filled with dirt",
    baseItem: "Dark Oak Stairs",
    anvilCode: "ssc095",
    variants: [
      { code: "a", name: "Copper", color: "#C87348" },
      { code: "b", name: "Light Gray", color: "#D8D3C9" },
      { code: "c", name: "Charcoal", color: "#2E2D2E" },
      { code: "d", name: "Peach", color: "#D8BC8B" },
      { code: "e", name: "Medium Gray", color: "#748876" },
      { code: "f", name: "Gray", color: "#91A9BA" },
      { code: "g", name: "Gray", color: "#9A8BAC" },
      { code: "h", name: "Dusty Rose", color: "#BB8894" },
      { code: "i", name: "Mauve", color: "#AB8677" },
      { code: "j", name: "Tan", color: "#B9AC92" },
      { code: "k", name: "Brown", color: "#8A6D4F" }
    ],
    positions: [
      { code: "back", name: "Back", description: "Appears at back of block" },
      { code: "corner", name: "Corner", description: "Corner of block" },
      { code: "raisedback", name: "Raised Back", description: "Raises 0.5 above block and appears behind item frame" },
      { code: "raisedforward", name: "Raised Forward", description: "Raises 0.5 above block and appears infront of item frame" }
    ],
    tags: ["pot", "ceramic", "planter", "garden", "plant", "decorative", "outdoor", "indoor", "simple", "minimal", "botanical", "colorful"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      b: "b.png",
      c: "c.png",
      d: "d.png",
      e: "e.png",
      f: "f.png",
      g: "g.png",
      h: "h.png",
      i: "i.png",
      j: "j.png",
      k: "k.png",
      pos_back: "ssc095back.png",
      pos_corner: "ssc095corner.png",
      pos_raisedback: "ssc095raisedback.png",
      pos_raisedforward: "ssc095raisedforward.png"
    }
  },
  {
    id: "ssc096",
    name: "Classic Support Beam 2",
    collection: "ssc",
    number: "096",
    category: "Structure",
    room: ["Exterior"],
    description: "A propped wooden support beam",
    baseItem: "Dark Oak Slab",
    anvilCode: "ssc096",
    variants: [
      { code: "a", name: "Russet", color: "#754411" }
    ],
    positions: [
      { code: "ceiling", name: "Ceiling", description: "Placed on ceiling" },
      { code: "ceilingcenter", name: "Ceiling Center", description: "Placed on center of ceiling" },
      { code: "left", name: "Left", description: "Left side of block" }
    ],
    tags: ["beam", "support", "structural", "classic", "wood", "wooden", "architectural", "exterior", "porch", "post", "traditional", "column"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_ceiling: "ssc096ceiling.png",
      pos_ceilingcenter: "ssc096ceilingcenter.png",
      pos_left: "ssc096left.png"
    }
  },
  {
    id: "ssc097",
    name: "Classic Support Beam 3",
    collection: "ssc",
    number: "097",
    category: "Structure",
    room: ["Exterior"],
    description: "A double-propped wooden support beam",
    baseItem: "Dark Oak Fence",
    anvilCode: "ssc097",
    variants: [
      { code: "a", name: "Russet", color: "#754411" }
    ],
    positions: [
      { code: "ceiling", name: "Ceiling", description: "Placed on ceiling" },
      { code: "ceilingcenter", name: "Ceiling Center", description: "Placed on center of ceiling" }
    ],
    tags: ["beam", "support", "structural", "classic", "wood", "wooden", "architectural", "exterior", "porch", "post", "traditional", "column"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_ceiling: "ssc097ceiling.png",
      pos_ceilingcenter: "ssc097ceilingcenter.png"
    }
  },
  {
    id: "ssc098",
    name: "Classic Support Beam 4",
    collection: "ssc",
    number: "098",
    category: "Structure",
    room: ["Exterior"],
    description: "A vertical wood and metal support beam",
    baseItem: "Dark Oak Fence Gate",
    anvilCode: "ssc098",
    variants: [
      { code: "a", name: "Russet", color: "#754411" }
    ],
    positions: [
      { code: "ceilingback", name: "Ceiling Back", description: "Placed on back of ceiling" },
      { code: "ceilingcenter", name: "Ceiling Center", description: "Placed on center of ceiling" },
      { code: "ceilingcorner", name: "Ceiling Corner", description: "Placed on corner of ceiling" },
      { code: "center", name: "Center", description: "Center of block" },
      { code: "right", name: "Right", description: "Right side of block" }
    ],
    tags: ["beam", "support", "structural", "classic", "wood", "wooden", "architectural", "exterior", "porch", "post", "traditional", "column"],
    colorTags: ["neutral", "brown"],
    images: {
      a: "a.png",
      pos_ceilingback: "ssc098ceilingback.png",
      pos_ceilingcenter: "ssc098ceilingcenter.png",
      pos_ceilingcorner: "ssc098ceilingcorner.png",
      pos_center: "ssc098center.png",
      pos_right: "ssc098right.png"
    }
  }
];

// Filter options shown in the catalog
const FILTER_OPTIONS = {
  category: [
    { value: "plants",  label: "Plants" },
    { value: "potted plants",    label: "Potted Plants" },
    { value: "rocks",  label: "Rocks" },
    { value: "outdoor",  label: "Outdoor" }
  ],
  room: [
    { value: "living",   label: "Living Room" },
    { value: "bedroom",  label: "Bedroom" },
    { value: "outdoor",  label: "Outdoor" },
    { value: "garden",   label: "Garden" },
    { value: "garage",   label: "Garage" },
    { value: "hallway",  label: "Hallway" }
  ],
  color: [
    { value: "black",  label: "Black" },
    { value: "brown",    label: "Brown / Wood" },
    { value: "green",    label: "Green" },
    { value: "blue",     label: "Blue" },
    { value: "pink",     label: "Pink / Mauve" },
    { value: "purple",   label: "Purple" },
    { value: "lime",  label: "Lime" }

  ],
}
